# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: public.ecr.aws/k5x9t2h7
  name: exabot-k8s
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

exabotK8s:
  env:
    # exabotK8s.env.queueUrl -- The SQS URL exabot will publis messages to
    queueUrl: ""
    # exabotK8s.env.configBucketId -- The S3 bucket where exabot will read it's configuration
    configBucketId: ""
  serviceAccount:
    # exabotK8s.serviceAccount.roleArn -- The ARN of the role that the service account will assume to access AWS resources
    roleArn: ""
  supportedArchitecture:
    # exabotK8s.supportedArchitecture.amd64 -- If true, the deployment will be scheduled on amd64 nodes
    amd64: true
    # exabotK8s.supportedArchitecture.arm64 -- If true, the deployment will be scheduled on arm64 nodes
    arm64: false
  memory:
    limit: "200Mi"
    request: "100Mi"
  cpu:
    request: "10m"
rbac:
  enabled: true
