{{- $roleArn := .Values.exabotK8s.serviceAccount.roleArn | required ".Values.exabotK8s.serviceAccount.roleArn is required." -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exabot-k8s
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $roleArn }}
